import Foundation

/// Whether a copy may be recorded at all.
///
/// This is the most consequential code in the app. macOS has an established convention
/// (nspasteboard.org) for marking a copy as "do not keep this" — password managers use it every
/// time you copy a password. A clipboard manager that ignores it writes credentials to a file on
/// disk. So the decision lives here, is pure, decides from the pasteboard's *type list* without
/// ever reading the content, and is tested exhaustively.
enum ClipboardPrivacyFilter {

    /// Copies carrying any of these are never recorded.
    static let excludedTypes: Set<String> = [
        // The modern convention.
        "org.nspasteboard.ConcealedType",       // confidential — password managers
        "org.nspasteboard.TransientType",       // momentary, about to be replaced
        "org.nspasteboard.AutoGeneratedType",   // not a deliberate user copy

        // Legacy markers still emitted by long-lived apps.
        "de.petermaurer.TransientPasteboardType",  // TextExpander, Butler, Textpander
        "com.typeit4me.clipping",                  // TypeIt4Me
        "Pasteboard generator type",               // Typinator
        "com.agilebits.onepassword",               // 1Password
    ]

    /// The type carrying the true originating bundle ID, when an app bothers to set it.
    static let sourceType = "org.nspasteboard.source"

    /// Universal Clipboard. Deliberately **not** excluded — a Handoff copy is a real copy the user
    /// made, and people expect to find it in history.
    static let remoteClipboardType = "com.apple.is-remote-clipboard"

    enum Decision: Equatable {
        case record
        case skipMarkedPrivate(type: String)
        case skipIgnoredApp(bundleID: String)
        case skipNothingUsable
    }

    static func decide(
        types: [String],
        sourceBundleID: String?,
        ignoredBundleIDs: Set<String>
    ) -> Decision {
        // Checked before anything else, and before the content is ever read.
        if let marker = types.first(where: { excludedTypes.contains($0) }) {
            return .skipMarkedPrivate(type: marker)
        }

        // The user's own list. It exists because the convention has a real gap: passwords copied
        // from password-manager *browser extensions* are frequently not marked concealed at all.
        if let bundleID = sourceBundleID, ignoredBundleIDs.contains(bundleID) {
            return .skipIgnoredApp(bundleID: bundleID)
        }

        guard !types.isEmpty else { return .skipNothingUsable }
        return .record
    }

    static func shouldRecord(
        types: [String],
        sourceBundleID: String?,
        ignoredBundleIDs: Set<String>
    ) -> Bool {
        decide(types: types, sourceBundleID: sourceBundleID, ignoredBundleIDs: ignoredBundleIDs) == .record
    }

    /// Prefers what the copying app declared over whatever happened to be frontmost. They differ
    /// whenever a background process or a helper puts something on the pasteboard — and the
    /// declared one is the one the ignore list should be matched against.
    static func resolveSource(declared: String?, frontmost: String?) -> String? {
        declared ?? frontmost
    }
}
