import XCTest
@testable import Sarvkrit

/// The most consequential tests in this project. A regression here writes passwords to a file on
/// disk, and it would do so silently — nothing visibly fails when a clipboard manager records one
/// copy too many.
final class ClipboardPrivacyFilterTests: XCTestCase {
    private let ordinary = ["public.utf8-plain-text", "NSStringPboardType"]

    // MARK: - The convention

    func testEveryExcludedTypeBlocksRecordingOnItsOwn() {
        for type in ClipboardPrivacyFilter.excludedTypes {
            XCTAssertFalse(
                ClipboardPrivacyFilter.shouldRecord(types: [type], sourceBundleID: nil, ignoredBundleIDs: []),
                "\(type) was recorded"
            )
        }
    }

    func testEveryExcludedTypeBlocksRecordingWhenMixedWithOrdinaryTypes() {
        // The real shape: a password manager puts the password on the pasteboard as plain text
        // *and* flags it concealed. Only checking the first type, or bailing out once a usable
        // type is found, would record it.
        for type in ClipboardPrivacyFilter.excludedTypes {
            XCTAssertFalse(
                ClipboardPrivacyFilter.shouldRecord(
                    types: ordinary + [type], sourceBundleID: "com.example.app", ignoredBundleIDs: []),
                "\(type) was recorded when mixed with plain text"
            )
            XCTAssertFalse(
                ClipboardPrivacyFilter.shouldRecord(
                    types: [type] + ordinary, sourceBundleID: nil, ignoredBundleIDs: []),
                "\(type) was recorded when listed first"
            )
        }
    }

    func testTheConventionsWeMustHonourAreAllPresent() {
        // Pinning the list itself: silently dropping one of these is the failure mode that matters,
        // and it wouldn't show up in any other test.
        let required = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "com.agilebits.onepassword",
        ]
        for type in required {
            XCTAssertTrue(ClipboardPrivacyFilter.excludedTypes.contains(type), "missing \(type)")
        }
    }

    func testTheDecisionNamesWhichMarkerBlockedIt() {
        let decision = ClipboardPrivacyFilter.decide(
            types: ordinary + ["org.nspasteboard.ConcealedType"],
            sourceBundleID: nil,
            ignoredBundleIDs: []
        )
        XCTAssertEqual(decision, .skipMarkedPrivate(type: "org.nspasteboard.ConcealedType"))
    }

    // MARK: - Ordinary copies still record

    func testAnOrdinaryCopyIsRecorded() {
        XCTAssertTrue(ClipboardPrivacyFilter.shouldRecord(
            types: ordinary, sourceBundleID: "com.apple.TextEdit", ignoredBundleIDs: []))
    }

    func testUniversalClipboardIsRecorded() {
        // Deliberately not excluded: a Handoff copy is a real copy the user made.
        XCTAssertTrue(ClipboardPrivacyFilter.shouldRecord(
            types: ordinary + [ClipboardPrivacyFilter.remoteClipboardType],
            sourceBundleID: nil,
            ignoredBundleIDs: []))
    }

    func testAnEmptyPasteboardIsNotRecorded() {
        XCTAssertEqual(
            ClipboardPrivacyFilter.decide(types: [], sourceBundleID: nil, ignoredBundleIDs: []),
            .skipNothingUsable)
    }

    // MARK: - The ignore list

    func testAnIgnoredAppIsNeverRecorded() {
        // This list exists because the convention has a known gap: passwords copied from password
        // manager *browser extensions* frequently aren't marked concealed at all.
        let decision = ClipboardPrivacyFilter.decide(
            types: ordinary,
            sourceBundleID: "com.1password.1password",
            ignoredBundleIDs: ["com.1password.1password"]
        )
        XCTAssertEqual(decision, .skipIgnoredApp(bundleID: "com.1password.1password"))
    }

    func testOtherAppsAreUnaffectedByTheIgnoreList() {
        XCTAssertTrue(ClipboardPrivacyFilter.shouldRecord(
            types: ordinary,
            sourceBundleID: "com.apple.TextEdit",
            ignoredBundleIDs: ["com.1password.1password"]))
    }

    func testAnUnknownSourceIsNotBlockedByTheIgnoreList() {
        // Nothing to match against; the marker check above is what protects this case.
        XCTAssertTrue(ClipboardPrivacyFilter.shouldRecord(
            types: ordinary, sourceBundleID: nil, ignoredBundleIDs: ["com.1password.1password"]))
    }

    func testMarkersAreCheckedBeforeTheIgnoreList() {
        // Ordering matters for the reported reason, and the marker is the more fundamental one.
        let decision = ClipboardPrivacyFilter.decide(
            types: ["org.nspasteboard.ConcealedType"],
            sourceBundleID: "com.example.ignored",
            ignoredBundleIDs: ["com.example.ignored"]
        )
        XCTAssertEqual(decision, .skipMarkedPrivate(type: "org.nspasteboard.ConcealedType"))
    }

    // MARK: - Source resolution

    func testDeclaredSourceWinsOverFrontmost() {
        // They differ whenever a helper or background process does the copying — and the declared
        // one is what the ignore list must be matched against.
        XCTAssertEqual(
            ClipboardPrivacyFilter.resolveSource(declared: "com.real.source", frontmost: "com.apple.finder"),
            "com.real.source")
    }

    func testFrontmostIsUsedWhenNothingIsDeclared() {
        XCTAssertEqual(
            ClipboardPrivacyFilter.resolveSource(declared: nil, frontmost: "com.apple.finder"),
            "com.apple.finder")
        XCTAssertNil(ClipboardPrivacyFilter.resolveSource(declared: nil, frontmost: nil))
    }

    func testAnAppIsIgnoredByItsDeclaredSourceEvenWhenAnotherAppIsFrontmost() {
        let source = ClipboardPrivacyFilter.resolveSource(
            declared: "com.1password.1password", frontmost: "com.apple.Safari")
        XCTAssertFalse(ClipboardPrivacyFilter.shouldRecord(
            types: ordinary, sourceBundleID: source, ignoredBundleIDs: ["com.1password.1password"]))
    }
}
